controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
health_check:
    path: /health-check
    methods: GET
    controller: App\Controller\HealthCheckAction::index
